/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

// import MessageUtils
import org.apache.commons.text.WordUtils
import printscript.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
