name: Lint
on: 
  pull_request:
  push:
  
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    - name: Run Ktlint
      uses: jlleitschuh/ktlint-gradle@main
